apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: rollouts-demo
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      steps:
        - setWeight: 20
        - pause: {duration: 20s}
        - setWeight: 40
        - pause: { duration: 20s }
        - setWeight: 100
        - pause: { duration: 20s }
      trafficRouting:
        traefik:
          weightedTraefikServiceName: rollouts-demo   # 對應 (3) 的 TraefikService 名稱
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue   # 發版時改成 :green 等即可觸發
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
