apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: { duration: 10m }
        - setWeight: 100
        - pause: { duration: 10m }
      trafficRouting:
        nginx:
          stableIngress: rollouts-demo-ingress
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    # rollout.yaml（節錄）  
    spec:
      strategy:
        canary:
          canaryService: rollouts-demo-canary
          stableService: rollouts-demo-stable
          steps:
            - setWeight: 20
            - pause: {}
            - setWeight: 40
            - pause: { duration: 10m }
            - setWeight: 100
            - pause: { duration: 10m }
          trafficRouting:
            traefik:
              # 這個名字要對到下方「加權的 TraefikService」
              weightedTraefikServiceName: rollouts-demo
              # （如需跨命名空間，可加 namespace: <ns>）
